### ISSUE TITLE
Quanti domicili digitali?

### ISSUE THREAD

**Issue by franthemanIT** [AgID/INAD_API_Extraction#10]
Dalle linee guida AGID sembra evincersi che un soggetto possa avere al massimo due domicili digitali registrati su INAD.
Questo avviene solo nel caso in cui si iscriva e come professionista e come cittadino.

"_Per quanto concerne l’elezione del domicilio digitale, solo i Professionisti hanno facoltà di eleggere nell’INAD sia un domicilio digitale professionale sia un domicilio digitale personale. La distinzione tra i due domicili digitali appartenenti al medesimo soggetto è resa evidente all’interno dell’INAD sia all’interessato, al momento dell’elezione del domicilio, sia agli utenti al momento della consultazione dell’INAD._ "

Tuttavia uno dei CF presenti nell'ambiente di collaudo presenta ben tre domicili digitali associati.
Cosa ci si deve attendere in ambiente di produzione?

**Comment by vintra73** [comment]
Buongiorno, 
in merito alla sua le evidenziamo che al momento dell'elezione di un DD come professionista ai sensi della legge n. 4/2013 lo stesso deve indicare la propria professione, tale necessità e la contemporanea possibilità che un soggetto posso svolgere contemporaneamente più professioni ai sensi della legge n. 4/2013 determina la circostanza da lei evidenziata.

Il periodo da lei indicato delle LG INAD non appare in contrapposizione in quanto nello stesso non si disconosce l'ipotesi che uno stesso soggetto possa svolgere più professioni ai sensi della legge n. 4/2013.

**Comment by franthemanIT** [comment]
Chiaro, grazie mille.
In caso di più DD professionali e nessun DD personale, c'è un modo per capire quale utilizzare per comunicazioni "al cittadino"?

**Comment by vintra73** [comment]
Salve,
in merito, considerato lo schema 

https://github.com/AgID/INAD_API_Extraction/blob/32f8ad40fc9a34af45898b537714bfa15cc8fbbb/inad_api_extraxtion.yaml#L433

che rappresenta la risposta per un singolo CF, in cui l'attributo digitalAddress cotiene l'array dei DD pubblicati su ANPR per lo stesso.

Ogni riferimento al DD veicolato nello schema

https://github.com/AgID/INAD_API_Extraction/blob/32f8ad40fc9a34af45898b537714bfa15cc8fbbb/inad_api_extraxtion.yaml#L334

prevede digitalAddress in cui è indicato il DD e practicedProfession riportante la professione o assente per il DD cittadino

in merito alla sua domanda, se la risposta non contiene un schema Element_Digital_Address con attributo practicedProfession assente indica che lo stesso non ha eletto DD come cittadino, colgo l'occasione per segnalare che allo stato l'elezione in INAD è facoltativa per i cittadini ai sensi del comma 1-bis, articolo 3-bis del CAD.

**Comment by franthemanIT** [comment]
Quindi, un domicilio digitale che arriva insieme all'attributo "practicedProfession" NON può essere usato per comunicazioni personali, anche se l'unico della lista? 
Se così fosse, trascorsi i 30 giorni di cui ai paragrafi 4 e 5 del capitolo 3 ("Acquisizione dall’INI-PEC dei domicili digitali dei
relativi professionisti"), ci dobbiamo attendere un array con due domicili digitali uguali indirizzo@dominio.it, uno con practicedProfession e uno senza? Oppure solo uno, senza attributo pracrticedProfession?

Credo che occorra chiarire bene come le prescrizioni delle linee guida si traducono in elementi/attributi delle response, altrimenti si rischiano fraintendimenti e implementazioni diverse da fornitore a fornitore.
Anche perché, ancora a monte, non si capisce che senso abbia un professionista presente già in INI-PEC presente in INAD solo come professionista...
