### ISSUE TITLE
Intervallo per polling

### ISSUE THREAD

**Issue by franthemanIT** [AgID/INAD_API_Extraction#11]
Ci sono indicazioni per impostare un intervallo di tempo congruo per il polling su /listDigitalAddress/state/{id} dello stato di avanzamento di una richiesta multipla?

Riferimento, "Documento operativo ModI su pattern di interazione", paragrafo 5.2 (Pattern non bloccanti RPC PULL (busy waiting)):
"Gli intervalli di polling possono essere definiti tra le parti."

**Comment by marcob71** [comment]
Mi associo alla richiesta perchè impatta sui diversi verticali da integrare.

**Comment by vintra73** [comment]
Buongiorno,
in merito alle richiesta di polling sui suggerisce un setting tra i 10 e 15 min.

Colgo l'occasione per segnalarvi che a valle della disponibilità del result set, lo stesso è mantenuto da INAD per al massimo 48h.
