### ISSUE TITLE
Response 401 di verify e extract - "error" e non "detail"

### ISSUE THREAD

**Issue by franthemanIT** [AgID/INAD_API_Extraction#12]
I due metodi "verify" ed "extract", in caso di response con status code 401, restituiscono un payload con chiave "error" e non "detail" come invece scritto nelle specifiche OPENAPI (file .yaml)

**Comment by vintra73** [comment]
Buongiorno abbiamo provveduto ad effettuare il fixing necessario per allineare il comportamento della API con quanto indicato nell'OpenAPI.

Ancora grazie per la segnalazione.

**Comment by franthemanIT** [comment]
Non che servisse, ma confermo che adesso restituisce "detail". In ambiente di collaudo ho fatto un verify con un token JWT scaduto. Ho anche aggiornato di conseguenza il mio script di interazione con INAD. 
Ne approfitto, oltre che per ringraziare, per mettere a disposizione lo script di cui sopra (è fra i miei repository) se risultasse utile per scopi didattici/divulgativi/promozionali a cavallo fra INAD e PDND.

**Comment by vintra73** [comment]
@franthemanIT grazie per il riscontro
