### ISSUE TITLE
consultazione delle API mediante stacco del JWT

### ISSUE THREAD

**Issue by marcyborg** [AgID/INAD_API_Extraction#13]
Salve,
ho letto nelle LG del processo di trust ai paragrafi 4.1, 4.2 e 4.3, non conosco bene il processo simile che si effettua sulla PDND; vorrei capire chi è l'ente presso cui richiedere il voucher che emette i claim presente nel JWT da inserire poi nell'header delle richieste?
Il mio scopo sarebbe di utilizzare in un'architettura a microservizi delle chiamate REST ad alcune API presenti nello YML per recuperare la presenza di un DD a partire da un CF.

Mi scuso se la domanda può risultare pleonastica.

Grazie.

**Comment by vintra73** [comment]
In merito all'utilizzo di PDND Interoperabilità quale authentication and authorization serve per l'accesso agli e-service resi disponibili da INAD per il tramite la stessa piattaforma, si rimanda alle [**Linee Guida sull’infrastruttura tecnologica della Piattaforma Digitale Nazionale Dati per l’interoperabilità dei sistemi informativi e delle basi di dati**](https://www.agid.gov.it/sites/default/files/repository_files/lg_infrastruttura_interoperabilita_pdnd.pdf) e più in generale al [**nuovo modello di interoperabilità delle Pubbliche Amministrazioni**](https://www.agid.gov.it/it/infrastrutture/sistema-pubblico-connettivita/il-nuovo-modello-interoperabilita).
