### ISSUE TITLE
Semantica parametro practicalReference

### ISSUE THREAD

**Issue by FSiniGE** [AgID/INAD_API_Extraction#14]
Buongiorno,
al fine di riuscire ad utilizzare propriamente le API offerte da INAD, chiederei cortesemente di specificare più chiaramente il significato del parametro `practicalReference`, presente nelle varie GET.

In particolare, 

- non è chiaro se sia atteso un valore particolare che faccia riferimento al "numero di protocollo" della pratica da notificare o, per esempio, sia una sorta di "costante" da utilizzare per indicare la tipologia di procedimento che ha portato alla necessità di richiedere il domicilio digitale
- non è chiaro se sia presente una qualche verifica del suddetto parametro lato INAD (e quali siano le eventuali logiche di controllo)

Rimanendo a disposizione per eventuali ulteriori chiarimenti sulla richiesta, si attende cortese riscontro.
Cordiali Saluti

**Comment by vintra73** [comment]
Buongiorno, in merito al parametro 'practicalReference' si precisa che lo stesso rappresenta un riferimento interno univoco al chiamante (Pubblica Amministro o Gestori di Pubblici Servizi) relativo al contesto entro cui l'invocazione è realizzata.

Un esempio di valorizzazione dello stesso è rappresentato dal "numero di protocollo interno" associato dalla Pubblica Amministrazione.

Relativamente alle azioni realizzata da INAD sullo stesso 'practicalReference' si evidenzia che non effettuato nessun controllo, in quanto il corretto popolamento del parametro è in carico al soggetto fruitore dell'e-service reso disponibile da INAD.

**Comment by FSiniGE** [comment]
Buongiorno,
grazie per il riscontro.

A questo punto, in assenza di particolari restrizioni sul campo in termini di lunghezza, pensavamo di inserire un riferimento utile "in senso generale" per la classificazione della procedura, ad esempio utilizzando un termine o un riferimento EuroVoc come incipit del campo, per poi inserire gli ulteriori dettagli del caso.

Ad esempio, un valore potrebbe essere "Infrazione-al-codice-della-strada_7944_Notifica verbali GG-MM-AAAA".

A vostro dire, potrebbe essere fattibile?
Grazie dell'attenzione

**Comment by vintra73** [comment]
Buongiorno,
fatta salva l'autonomia nel popolamento di 'practicalReference', l'utilizzo della thesaurus EuroVoc è molto interessate ed in merito suggerisco di utilizzare di referenziare la versione e Concept URI (ad esempio http://eurovoc.europa.eu/7944-v4.2_<personal reference>, in dove personal reference riporta il riferimento interno al contesto entro cui l'invocazione è realizzata).

In merito alla dimensione del campo 'practicalReference' si conferma che non vi sono restrizioni di lunghezza (si segnala che la request in cui è presente lo stesso viene persistita in un campo di tipo json).
