### ISSUE TITLE
Endpoint corretti e 401

### ISSUE THREAD

**Issue by SkydivingAngel** [AgID/INAD_API_Extraction#15]
Salve vorrei chiedere conferma dell'endpoint corretto da utilizzare per il metodo (es: verify) con dati provenienti dal csv di esempio:
https://domiciliodigitaleapi.oscl.infocamere.it/rest/inad/v1/domiciliodigitale/verify/MNTCRL93H18I452Y
oppure
https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/verify/MNTCRL93H18I452Y

Inoltre la risposta è sempre di tipo 401.
Quale tipo di autenticazione è richiesta (presumo oauth2 con jwt) e come ottenete quindi tali credenziali.

Cordiali Saluti

**Comment by vintra73** [comment]
Buongiorno,
in merito alle sue le segnalo:

- url del server che espone le API è https://api.inad.gov.it/rest/inad/v1/domiciliodigitale
- in merito jwt necessario per l'autenticazione le ricordo che il trust tra INAD e i sistemi ICT delle PA è realizzato per il tramite della infrastruttura tecnologica della [Piattaforma Digitale Nazionale Dati interoperabilità](https://www.interop.pagopa.it/)
