### ISSUE TITLE
Richiesta di esempio pratico chiamata extract nella documentazione

### ISSUE THREAD

**Issue by Magnosys** [AgID/INAD_API_Extraction#17]
buongiorno,

Sto effettuando le prime chiamate alla ws /extract
ma mi ritorna sempre errore 400 bad request

mi sarebbe comodo avere una chiamata di esempio raw a cui fare riferimento per costruire bene la chiamata.

la chiamata che faccio e' questa:

GET /rest/inad/v1/domiciliodigitale/extract/MNCDVD96E28B519P HTTP/1.1
Authorization: Bearer eyJ0eXAiOixxxx.eyJhdWQxxxxxx
Host: domiciliodigitaleapi.oscl.infocamere.it

mi sembra di fare tutto correttamente tranne una cosa, nella documentazione ce scritto che bisogna passare in query il practicalReference, ma dentro la chiamata come deve essere inserito?

**Comment by franthemanIT** [comment]
/rest/inad/v1/domiciliodigitale/extract/MNCDVD96E28B519P?practicalReference=PROVA_PRACTICALREFERENCE

**Comment by Magnosys** [comment]
Ringrazio per la risposta tempestiva.

Cordiali Saluti.
