### ISSUE TITLE
Invalid Bearer JWT Token

### ISSUE THREAD

**Issue by aipicinum** [AgID/INAD_API_Extraction#18]
Buongiorno,
provando a invocare con postman in GET https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/extract/{TRVVCN73H02L259I} ricevo sempre 
{
    "status": 401,
    "type": "UNAUTHORIZED",
    "detail": "Invalid Bearer JWT Token"
}
anche se ho generato correttamente il token JWT:
{
    "access_token": "ey..........",
    "expires_in": 600,
    "token_type": "Bearer"
}
Sicuramente sbaglio qualcosa ma dopo diversi tentativi non sono riuscito a risolvere, potete aiutarmi?

**Comment by franthemanIT** [comment]
Nella request dove lo metti il token?
Va nell'header
"Authorization" : "Bearer ey....."

**Comment by aipicinum** [comment]
Allego screenshot postman:
![image](https://github.com/AgID/INAD_API_Extraction/assets/140488116/3f6c74a7-b1e8-43f1-a637-dbf0ee99e5be)

**Comment by franthemanIT** [comment]
Consiglio l'uso del tool di debug del JWT disponibile nell'interfaccia PDND

**Comment by aipicinum** [comment]
Buongiorno, e grazie per la risposta.
Il debug è disponibile solo per la client assertion e non per lo step successivo di invocazione del servizio per la verifica del domicilio digitale.
Da Postman riesco ad ottenere il token, non riesco a chiamare il servizio di estrazione successico.
Lasciando perdere Postman, a me serve poter richiamare da un'applicazione JAVA i servizi di estrazione dei domicili digitali.
Interroghiamo già con successo INI-PEC e abbiamo bisogno di integrare i nuovi servizi per il recupero dei domicili digitali.
Non ho trovato un esempio di implementazione (in un qualsiasi linguaggio) delle chiamate ai nuovi servizi, nè delle indicazioni su cosa debba contenere e come debba essere strutturata la chiamata.
Provando a richiamare il servizio per l'ottenimento del token da codice JAVA ho ottenuto "javax.net.ssl.SSLException: Received close_notify during handshake", non so bene se ho configurato correttamente i parametri della chiamata non avendo a disposizione una documentazione specifica.

Potete darmi delle indicazioni per il richiamo dei servizi di INAD? 
Ho necessità di integrarli nell'applicazione sulla quale lavoro.

Grazie

**Comment by franthemanIT** [comment]
Per mia esperienza (limitata) se la client assertion passa il debug allora si sta inviando il token ottenuto con la assertion a un AUD/URL sbagliato. Sia la PDND sia INAD hanno ambienti distinti per collaudo e produzione.

Fra i miei repository ce ne sono un paio con implementazioni delle chiamate e link alla documentazione disponibile (già le specifiche openapi sembrerebbero sufficienti).

**Comment by aipicinum** [comment]
Grazie mille, per la risposta.
Non avevo visto i repository disponibili, proverò ad usarli come guida per risolvere i miei problemi lato java.
Volevo chiedere un'altra cosa, va richiesta una nuova client assertion prima di ogni richiesta di token? Oppure la client assertion una volta ottenuta può essere memorizzata e riutilizzata?

Grazie ancora
