### ISSUE TITLE
Tempo di attesa molto altro per response elaborazione liste massive

### ISSUE THREAD

**Issue by marcob71** [AgID/INAD_API_Extraction#19]
Buon pomeriggio,
stiamo avendo problemi nell'interrogare, sull'ambiente di produzione, il servizio di richiesta massiva tramite pdnd.
Di fatto ogni giorno ci va a buon fine, e quindi con l.a response dei cf aventi o meno la pec, solo per la prima interrogazione. Le sucessive rimangono in stato IN_ELABORAZIONE anche dopo diverse ore.
Come esempio riporto le segiuenti interrogazioni massive eseguite in data odierna:

_{
    "state": "PRESA_IN_CARICO",
    "message": "Richiesta elenco presa in carico",
    "id": "c62e69b1-9d23-4649-b291-909815ae0cdb",
    "dateTimeRequest": "2023-08-01T08:20:07Z"
}_
la cui ressponse ha dato l'elenco richiesto nel giro di qualche minuto.

e le seguenti due:
_{
    "state": "PRESA_IN_CARICO",
    "message": "Richiesta elenco presa in carico",
    "id": "ed93ce97-3df6-4279-928a-0fa139ed3e20",
    "dateTimeRequest": "2023-08-01T08:25:58Z"
}_

e

_{
    "state": "PRESA_IN_CARICO",
    "message": "Richiesta elenco presa in carico",
    "id": "cc94aebf-cd9c-4f50-a554-0875983c1e8d",
    "dateTimeRequest": "2023-08-01T08:56:21Z"
}_

che ancora adesso (ore 16:46 del 01/08/23) hanno come state 
_{
    "state": "IN_ELABORAZIONE",
    "message": "Richiesta elenco in fase di processamento"
}_

è possibile verificare da cosa dipende questa lunga attesa?

grazie

**Comment by vintra73** [comment]
buonsera @marcob71,
grazie per la segnalazione, abbiamo avviato l'analisi del problema individuando il bug e contiamo di darle un riscontro quanto prima del fixing.

**Comment by vintra73** [comment]
buongiorno @marcob71,
le segnalo che abbiamo effettuato il fixing.

Grazie
