### ISSUE TITLE
Errore servizio

### ISSUE THREAD

**Issue by antoreco** [AgID/INAD_API_Extraction#20]
Buongiorno,
ricevo l'errore 401 "Unauthorized" dai servizi, ho provato a contattare PDND ma dal loro lato mi confermato vada tutto a buon fine. Sono in fase di collaudo, l'e-service che sto utilizzando è "INAD API PUBBLICHE CONSULTAZIONE", perchè "INAD CONSULTAZIONE DD" non mi risulta nel catalogo di collaudo, quale potrebbe essere il problema?
Cordiali saluti.

**Comment by vintra73** [comment]
Buongiorno,
in merito alle sue:
1. relativamente al problema da lei espresso sarebbe necessario avere maggiori riferimenti relativamente alla request, ci risulta impossibile rintracciare la sua richiesta con quanto da lei indicato, sarebbe utile avere riferimenti al idclient da cui effettua la chiamata e il jti del token PDND utilizzato
2. relativamente al naming degli e-service abbiamo deciso di utilizzare naming differenti per i due ambienti PDND per questo non trova l'e-service da lei indicato

**Comment by antoreco** [comment]
Buongiorno,

   le aggiungo le informazioni da lei richieste:

   Il client id: 2893ed6d-c1d3-48ff-8c8c-8325c4e991e9

   Il jti: ac1bc666-0070-4e3e-88f0-61e6f65313bf

   Cordiali saluti.

   Da "vincenzo travascio" ***@***.***
   A "AgID/INAD_API_Extraction" ***@***.***
   Cc "antoreco" ***@***.***,"State change" ***@***.***
   Data Fri, 25 Aug 2023 09:09:51 -0700
   Oggetto Re: [AgID/INAD_API_Extraction] Errore servizio (Issue #20)

   Buongiorno,
   in merito alle sue:
    1. relativamente al problema da lei espresso sarebbe necessario avere maggiori riferimenti relativamente alla request, ci risulta impossibile rintracciare la sua richiesta con quanto da lei indicato, sarebbe utile avere riferimenti al idclient da cui effettua la chiamata e il jti del token PDND utilizzato
    2. relativamente al naming degli e-service abbiamo deciso di utilizzare naming differenti per i due ambienti PDND per questo non trova l'e-service da lei indicato

**Comment by antoreco** [comment]
La request è stata effettuata in ambiente PDND collaudo per il comune di Pietraperzia.

   Da "vincenzo travascio" ***@***.***
   A "AgID/INAD_API_Extraction" ***@***.***
   Cc "antoreco" ***@***.***,"State change" ***@***.***
   Data Mon, 28 Aug 2023 09:30:36 -0700
   Oggetto Re: [AgID/INAD_API_Extraction] Errore servizio (Issue #20)

   La request è stata effettuata nell'ambiente PDND collaudo? Per quale PA?

   Grazie

**Comment by diegopedone** [comment]
Potete provare nuovamente a fare una richiesta così da riuscire a monitorare tutto il flusso? Grazie in anticipo

**Comment by antoreco** [comment]
Ho rifatto la chiamata.

   Il client id è:2893ed6d-c1d3-48ff-8c8c-8325c4e991e9
   Il jti è: 61be3669-fda5-452d-ace2-63d891fe8582
   Da "diegopedone" ***@***.***
   A "AgID/INAD_API_Extraction" ***@***.***
   Cc "antoreco" ***@***.***,"State change" ***@***.***
   Data Tue, 29 Aug 2023 06:22:25 -0700
   Oggetto Re: [AgID/INAD_API_Extraction] Errore servizio (Issue #20)

   Potete provare nuovamente a fare una richiesta così da riuscire a monitorare tutto il flusso? Grazie in anticipo

**Comment by diegopedone** [comment]
Salve, 
per effettuare un'analisi approfondita della problematica sarebbe possibile ripetere il test e fornirci anche la richiesta http effettuata compresa di header.
Grazie in anticipo.

**Comment by antoreco** [comment]
Salve,

   allego la schermata della chiamata..

   il jti è: 3986c173-e38c-4a0d-9106-b6a487865cdb

   Da "diegopedone" ***@***.***
   A "AgID/INAD_API_Extraction" ***@***.***
   Cc "antoreco" ***@***.***,"State change" ***@***.***
   Data Wed, 30 Aug 2023 01:19:27 -0700
   Oggetto Re: [AgID/INAD_API_Extraction] Errore servizio (Issue #20)

   Salve,
   per effettuare un'analisi approfondita della problematica sarebbe possibile ripetere il test e fornirci anche la richiesta http effettuata compresa di header.
   Grazie in anticipo.

**Comment by antoreco** [comment]
Buongiorno,

   qualche giorno fa c'eravamo sentiti per ripetere il test sui servizi INAD collaudo, non ho ricevuto risposta però...

   Cordiali saluti

**Comment by diegopedone** [comment]
Salve sono in attesa dell'allegato contenente la richiesta fatta e l'header della stessa, potete allegarlo in formato json

**Comment by antoreco** [comment]
Buon pomeriggio,
client id: 2893ed6d-c1d3-48ff-8c8c-8325c4e991e9
jti: 3986c173-e38c-4a0d-9106-b6a487865cdb

Git non permette di allegare file formato json, quindi lo mando testualmente:

{
	"info": {
		"_postman_id": "344fe522-43a5-46c9-8ead-91f952a4e2a1",
		"name": "InadRequest",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/extract/RRANGL74M28R701V",
			"protocolProfileBehavior": {
				"disabledSystemHeaders": {
					"accept": true
				}
			},
			"request": {
				"auth": {
					"type": "bearer",
					"bearer": [
						{
							"key": "token",
							"value": "eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJkb21pY2lsaW9kaWdpdGFsZWFwaS5vc2NsLmluZm9jYW1lcmUuaXQiLCJzdWIiOiIyODkzZWQ2ZC1jMWQzLTQ4ZmYtOGM4Yy04MzI1YzRlOTkxZTkiLCJuYmYiOjE2OTM5MjM0OTAsInB1cnBvc2VJZCI6IjViNWVjZTdjLTM4MzAtNDFmYy04ZWIyLWFkZTUxMzlhNGE0YSIsImlzcyI6InVhdC5pbnRlcm9wLnBhZ29wYS5pdCIsImV4cCI6MTY5NDAwOTg5MCwiaWF0IjoxNjkzOTIzNDkwLCJjbGllbnRfaWQiOiIyODkzZWQ2ZC1jMWQzLTQ4ZmYtOGM4Yy04MzI1YzRlOTkxZTkiLCJqdGkiOiIyNjI1OWNmMy05MjI2LTRmODktYWJlOS03YzNjN2JlYjJmYmEifQ.3zTeuvi6Mgmpp1OdgxrjXFiYzIdlQqNPrQAKG_YxRcAZSQE1KwcTqib6qr0J1A25b6cn9qACXZf2VjkKEzgdey7dDvD6OH70RAQtH12tnNYVeMXOivgSVCnzqS_06VCtMkjGP2D2T4RNp9MG-IBfYPEr5cafcJVCiXZhdBsf3c0rTSbXCOZxlR35uO9v16P9tlowIoZO2wQPFz7awhds_uWwCXjCi5dfqQNEqVyIVrVp4JrgKpvjh8eszjaaaZSaplSrf1DA9oSVNzTisCW_SAq20740Fh33B6tEezTIiy5g0gvMOaPVrvd9YDsLSQz1WwTYctr8GRb1Z-nudelgIg",
							"type": "string"
						}
					]
				},
				"method": "GET",
				"header": [
					{
						"key": "Content-Type",
						"value": "application/json",
						"type": "default"
					},
					{
						"key": "Accept",
						"value": "application/json,application/problem+json",
						"type": "default"
					},
					{
						"key": "aud",
						"value": "domiciliodigitaleapi.oscl.infocamere.it",
						"type": "default",
						"disabled": true
					},
					{
						"key": "practicalReference",
						"value": "abc123",
						"type": "default"
					}
				],
				"url": {
					"raw": "https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/extract/RRANGL74M28R701V",
					"protocol": "https",
					"host": [
						"api",
						"inad",
						"gov",
						"it"
					],
					"path": [
						"rest",
						"inad",
						"v1",
						"domiciliodigitale",
						"extract",
						"RRANGL74M28R701V"
					]
				}
			},
			"response": []
		}
	]
}

**Comment by pippob02** [comment]
Buon pomeriggio,
nella issue menzionata in alto è trattata la nuova problematica sulla chiamata Inad. Siamo ancora in attesa di supporto.
Grazie

**Comment by pippob02** [comment]
@franthemanit abbiamo provato il tuo progetto parlaconinad2 e dà lo stesso errore 401 (per ottenere l'access token abbiamo dovuto modificare due link ormai obsoleti).

**Comment by franthemanIT** [comment]
Ah, grazie. Me lo segnali nel repository così appena possibile provo anche io?

**Comment by franthemanIT** [comment]
> @franthemanIT abbiamo provato il tuo progetto parlaconinad2 e dà lo stesso errore 401 (per ottenere l'access token abbiamo dovuto modificare due link ormai obsoleti).

Lo script ha al suo interno gli url sia di collaudo sia di produzione, vanno commentati e scommentati in base a ciò che serve.

Io ho provato adesso, in produzione, e funziona correttamente (nel senso che non mi respinge il token).

Consiglio di verificare la client assertion prodotto tramite il "debug client assertion" presente nel back office di PDND (che per esempio segnala se si sta cercando di entrare nell'ambiente di test con i dati di produzione o viceversa).

**Comment by pippob02** [comment]
grazie

**Comment by Jill97** [comment]
Buongiorno è da ieri che testo il servizio ListDigitalAddress e mi ritorna un 500, cosa che non succedeva scorsa settimana,c'è qualche problema lato servizio?
