### ISSUE TITLE
Error 401 "Invalid Bearer JWT Token" durante la richiesta a INAD

### ISSUE THREAD

**Issue by pippob02** [AgID/INAD_API_Extraction#21]
Ciao,
sono uno sviluppatore che si sta occupando dell'integrazione INAD su un applicativo della nostra azienda. 
Siamo su collaudo e stiamo utilizzando l'e-service INAD API PUBBLICHE CONSULTAZIONE. 
Per soddisfare la nostra richiesta abbiamo fatto generare in primo luogo la chiave privata, utile a generare l'assertion (assertion key ha passato con successo i controlli del debug) che chiamando https://auth.uat.interop.pagopa.it/token.oauth2. riesce a farci ottenere il token da utilizzare per la chiamata al servizio INAD. 
    "client_id": "dd7b1ac0-0c84-4557-88e1-1c8f7a15e061"
    "jti": "d32abdb8-a508-4196-9442-e4cb306ead5f"

Per la chiamata al sevizio INAD (https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/extract/RRANGL74M28R701V?practicalReference=asd) aggiungiamo nell'header Authorization: Bearer <(token ottenuto nella chiamata precedente)> (come da guida) e come risposta otteniamo il seguente errore:
{
    "status": 401,
    "type": "UNAUTHORIZED",
    "detail": "Invalid Bearer JWT Token"
}

Guide utilizzate:
[Generazione dell'assertion e successivo token](https://docs.pagopa.it/f.a.q.-per-integratori/knowledge-base-di-piattaforma-notifiche/focus-su-interoperabilita-e-generazione-voucher-per-send-uat-piattaforma-notifiche/focus-su-creazione-richiesta-di-fruizione-generazione-voucher-per-send-uat-piattaforma-notifiche)
[Richiesta a INAD](https://editor.swagger.io/url=https://raw.githubusercontent.com/AgID/INAD_API_Extraction/main/inad_api_extraxtion.yaml)

Chiediamo supporto a riguardo e siamo reperibili in ogni modo per risolvere il problema

**Comment by vintra73** [comment]
il tema è trattato nella issue https://github.com/AgID/INAD_API_Extraction/issues/20

**Comment by pippob02** [comment]
abbiamo notato quella issue ma è in stallo da settimane

**Comment by vintra73** [comment]
la invito ad utilizzare l'indicato issue per permetterci di concentrare le rispsote

grazie

**Comment by paperino-testing-apis** [comment]
> Ciao, sono uno sviluppatore che si sta occupando dell'integrazione INAD su un applicativo della nostra azienda. Siamo su collaudo e stiamo utilizzando l'e-service INAD API PUBBLICHE CONSULTAZIONE. Per soddisfare la nostra richiesta abbiamo fatto generare in primo luogo la chiave privata, utile a generare l'assertion (assertion key ha passato con successo i controlli del debug) che chiamando https://auth.uat.interop.pagopa.it/token.oauth2. riesce a farci ottenere il token da utilizzare per la chiamata al servizio INAD. "client_id": "dd7b1ac0-0c84-4557-88e1-1c8f7a15e061" "jti": "d32abdb8-a508-4196-9442-e4cb306ead5f"
> 
> Per la chiamata al sevizio INAD (https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/extract/RRANGL74M28R701V?practicalReference=asd) aggiungiamo nell'header Authorization: Bearer <(token ottenuto nella chiamata precedente)> (come da guida) e come risposta otteniamo il seguente errore: { "status": 401, "type": "UNAUTHORIZED", "detail": "Invalid Bearer JWT Token" }
> 
> Guide utilizzate: [Generazione dell'assertion e successivo token](https://docs.pagopa.it/f.a.q.-per-integratori/knowledge-base-di-piattaforma-notifiche/focus-su-interoperabilita-e-generazione-voucher-per-send-uat-piattaforma-notifiche/focus-su-creazione-richiesta-di-fruizione-generazione-voucher-per-send-uat-piattaforma-notifiche) [Richiesta a INAD](https://editor.swagger.io/url=https://raw.githubusercontent.com/AgID/INAD_API_Extraction/main/inad_api_extraxtion.yaml)
> 
> Chiediamo supporto a riguardo e siamo reperibili in ogni modo per risolvere il problema
Ciao, dunque provo ad aiutarti io (ci ho messo un po' a mettere in piedi tutto).

La richiesta Token in (Collaudo) è eseguita presso questo endpoint: https://auth.uat.interop.pagopa.it/token.oauth2
In (Produzione): https://auth.interop.pagopa.it/token.oauth2

--------------------------------------------------------------

Poi, naturalmente come ben documentato, dovrai usare altri endpoint a seconda dell'ambiente utilizzato:

Per richieste puntuali (Collaudo):
https://domiciliodigitaleapi.oscl.infocamere.it/rest/inad/v1/domiciliodigitale/extract/DPRRFL62A16B581X?practicalReference=abc123

Per richieste asincrone massive (Collaudo):
https://domiciliodigitaleapi.oscl.infocamere.it/rest/inad/v1/domiciliodigitale/listDigitalAddress
https://domiciliodigitaleapi.oscl.infocamere.it/rest/inad/v1/domiciliodigitale/listDigitalAddress/state/952d8f21-2829-495a-9bd2-4dec28fadba2
https://domiciliodigitaleapi.oscl.infocamere.it/rest/inad/v1/domiciliodigitale/listDigitalAddress/response/17e21e38-55cd-4c41-a8b6-ced702d79c79

--------------------------------------------------------------

Per richieste puntuali (Produzione):
https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/extract/RRANGL74M28R701V?practicalReference=abc123

Per richieste asincrone massive (Produzione):
https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/listDigitalAddress
https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/listDigitalAddress/state/952d8f21-2829-495a-9bd2-4dec28fadba2
https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/listDigitalAddress/response/17e21e38-55cd-4c41-a8b6-ced702d79c79
