### ISSUE TITLE
Errore 404

### ISSUE THREAD

**Issue by antoreco** [AgID/INAD_API_Extraction#23]
Buongiorno, 
utilizzando i servizi, ricevo errore 404 "CF not found", sia che uso codici fiscali validi, sia che li uso non validi... ci sarebbero dei CF di test da poter utilizzare?
Grazie

**Comment by vintra73** [comment]
Buongiorno, 
può trovare un sample di CF valido nell'ambient PDND collaudo all'URL https://github.com/AgID/INAD_API_Extraction/blob/main/datasetSample.csv
