### ISSUE TITLE
Errore 500 

### ISSUE THREAD

**Issue by dominickgl** [AgID/INAD_API_Extraction#24]
Salve,
da pochi giorni, utilizzando il servizio d'estrazione ricevo il seguente errore:

{"timestamp":"2023-10-03T10:34:45.654+00:00","status":500,"error":"Internal Server Error","path":"/v1/domiciliodigitale/extract/TRVVCN73H02L259I"}

Ho effettuato la verifica per l'assertion con il tool messo a disposizione della piattaforma e mi dà esito positivo.
L'endpoint utilizzato per la richiesta è il seguente:
https://domiciliodigitaleapi.oscl.infocamere.it/rest/inad/v1/domiciliodigitale/extract/TRVVCN73H02L259I?practicalReference=testdeda

possibili soluzioni?
Grazie in anticipo

**Comment by Hdemografici** [comment]
avevamo anche noi lo stesso errore, poi da qualche ora ha ripreso a funzionare correttamente senza fare modifiche

**Comment by dominickgl** [comment]
Si, ho riprovato ed adesso funziona correttamente.
