### ISSUE TITLE
recuperoDomicilioDigitale - practicedProfession sempre a null

### ISSUE THREAD

**Issue by zoffoliluca** [AgID/INAD_API_Extraction#26]
Sto testando il metodo recuperoDomicilioDigitale : GET /extract/{codice_fiscale}

Tra i campi di risposta ho 'practicedProfession ' 

"La valorizzazione di practicedProfession è prevista solo per la fattispecie “professionisti che svolgono una professione non organizzata in ordini, albi o collegi ai sensi della legge n. 4/2013 (di seguito Professionisti)”.

Ho provato con vari codici fiscali di professionisti (Avvocati, Geometri, etc.) ma il campo 'practicedProfession ' è sempre null.

Avreste almeno un codice fiscale per testare il  practicedProfession?

Grazie

**Comment by franthemanIT** [comment]
ai tempi TRVVCN73H02L259I aveva 3 domicili e due professioni (in ambiente di collaudo)

**Comment by zoffoliluca** [comment]
> ai tempi TRVVCN73H02L259I aveva 3 domicili e due professioni (in ambiente di collaudo)

Grazie della risposta. Dove trovo le info relative all'ambiente di collaudo?

**Comment by franthemanIT** [comment]
Le specifiche sono uguali, ovviamente va creato un client eservice in ambiente di collaudo della pdnd (dove trovi anche gli url, che credo siano anche nel file yaml)

**Comment by vintra73** [comment]
Buongiorno @zoffoliluca, in merito alla sua le ricordo che l'attuale repo github è stato creato per condividere le esperienze sull'utilizzo delle API per l'estrazione dei DD da INAD, tutti i riferimenti sono disponibili su PDND rispettivamente collaudo e produzione.
