### ISSUE TITLE
verificaDomicilioDigitale - Bad Request

### ISSUE THREAD

**Issue by zoffoliluca** [AgID/INAD_API_Extraction#27]
Nello yaml ho le seguenti definizioni :

**Digital_Address**:
      pattern: ^[a-zA-Z0-9_.+-][+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$](mailto:+@[a-zA-Z0-9-]+%5C.%5ba-zA-Z0-9-.%5d+$)
      type: string
      description: Indirizzo PEC del Domicilio Digitale
      example: [example@pec.it](mailto:example@pec.it)
    **UUID**:
      maxLength: 40
      minLength: 20
      pattern: ^[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$
      type: string
      description: Codice univoco della richiesta di elaborazione Report
      example: f8c3de3d-1fea-4d7c-a8b0-29f63c4c3454

Sto testando il metodo **verificaDomicilioDigitale** tramite il client (generato dallo yaml).

Viene fatta una GET in questo modo : 
[https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/verify/CIOFBA80B29D810R?digital_address=fcioe%252540pecagrotecnici.it&since=2017-07-21&practicalReference=test](https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/verify/CIOFBA80B29D810R?digital_address=fcioe%252540pecagrotecnici.it&since=2017-07-21&practicalReference=test)

Il client effettua in automatico un encode del "digital_address" ad UTF-8 (credo sia corretto) ma il pattern (tramite le RegEx) poi lo rifiuta ed ottengo una BAD REQUEST (a causa della @ codificata)

Se da Postman faccio una GET secca senza "encode" dei campi, funziona.
[https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/verify/CIOFBA80B29D810R?digital_address=fcioe@pecagrotecnici.it&since=2017-07-21&practicalReference=test](https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/verify/CIOFBA80B29D810R?digital_address=fcioe@pecagrotecnici.it&since=2017-07-21&practicalReference=test)
 
Non ne sono certo ma almeno per le **email** e lo **uuid** si possono usare i relativi format

Specifiche OpenAPI : [https://spec.openapis.org/registry/format/](https://spec.openapis.org/registry/format/)

Un po' come è stato già fatto qui nello yaml :
dateTimeCheck:
          type: string
          description: Data/Ora estrazione in formato ISO 8601 <yyyy-MM-dd'T'HH:mm:ssZ>
          format: date-time
          example: '2017-07-21T17:32:28Z'

Fatemi sapere se è un bug o una gestione NON corretta da parte mia (anche se il client che è autogenerato a partire dallo yaml)

Grazie

**Comment by vintra73** [comment]
Buongiorno,
in primis le chiedo scusa per il ritardo nella risposta.

Relativamente alla sua richiesta, come da lei constatato, la API implementata rispetta la firma dichiarata.

In merito alla sua indicazione delle specifiche OpenAPI, allo stato non è prevista un'adeguamento alle stesse.

Grazie
