### ISSUE TITLE
Errore Token su qualsiasi chiamata

### ISSUE THREAD

**Issue by Lovecraft81** [AgID/INAD_API_Extraction#28]
Buonasera, 
stiamo provando ad effettuare una chiamata con Postman al servizio INAD  in ambiente di interoperabilità collaudo.
Abbiamo effettuato la connessione nel sistema di interoperabilità collaudo e ottenuto il corretto client_assertion (verificato anche tramite il degub presente all'interno dell'interoperabilità)
Fatto questo, tramite l'API https://auth.uat.interop.pagopa.it/token.oauth2 abbiamo ottenuto il token per l'e_service INAD API PUBBLICHE CONSULTAZIONE.
Quando effettuiamo una qualsiasi chiamata ai servizi esposti su https://api.inad.gov.it/rest/inad/v1/domiciliodigitale otteniamo in risposta {"status":401,"type":"UNAUTHORIZED","detail":"Invalid Bearer JWT Token"}.
Dove stiamo sbagliando? C'è qualche ulteriore configurazione non riportata nella guida?

Segnalo inoltre che la guida, pur essendo uno yalm, non è leggibile con swagger.

Allego un dettaglio della chiamata.

POST https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/listDigitalAddress
401
82 ms
POST /rest/inad/v1/domiciliodigitale/listDigitalAddress HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJkb21pY2lsaW9kaWdpdGFsZWFwaS5vc2NsLmluZm9jYW1lcmUuaXQiLCJzdWIiOiI1ZmQ2N2JiYi04ZGQ0LTQ4NjUtODAzMi1iYjQ0MzExNWRiNTIiLCJuYmYiOjE3MDM4NTY4MzksInB1cnBvc2VJZCI6IjI4N2IzZWNhLWMwZDMtNDQzZS05MTU0LTUxNGVlZDMxMmI5MCIsImlzcyI6InVhdC5pbnRlcm9wLnBhZ29wYS5pdCIsImV4cCI6MTcwMzk0MzIzOSwiaWF0IjoxNzAzODU2ODM5LCJjbGllbnRfaWQiOiI1ZmQ2N2JiYi04ZGQ0LTQ4NjUtODAzMi1iYjQ0MzExNWRiNTIiLCJqdGkiOiIzNGFkMTIyMS1kZTc5LTRiMDgtODY5Ny0yNmZhZDBlNmY3MzYifQ.DVg8MokPyaal2igBW1s8l0D0klecq60d-ruWNHxdfhbiKB1GgHbsOMRkdxL6sC-hZogvDO9HYBS708DOvgL3GIH5iQJ-yWjs6Qqz69Oe7BiQQ5rJkLQqGBH5N8TfUC_WxjfzgGIdlyf06uUU-K6qCT8uUjAa2tCPqUKDaOyGE5J90oxJrvRNY5GY50VV5sTBEV4opAjk9PQdfMBww28t8bvOam2c_NlUbYnlTa0pK-4svu7M-toVndeF0e7B7iH3AJxL3mWi4rIcqOZE1jZhwCrt5eLwvYQq9MPQgd9I4dw7KSKtYrumn0DQsbw8Gzy9DL-zcn_aBvA8QAhNGZ4Fkw
User-Agent: PostmanRuntime/7.36.0
Postman-Token: b94af0a0-b26e-4288-93a0-584a3dd1c83a
Host: api.inad.gov.it
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 82
Cookie: 34c274f102110c314e7714720f9f288f=d3d61b9c138776e793e708bf15aa1cae
 
{
"codiciFiscali": [
"RGGSNO93E57C619T"
],
"praticalReference": "1234"
}
 
HTTP/1.1 401 Unauthorized
Content-Type: application/json
Content-Length: 72
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Frame-Options: DENY
X-XSS-Protection: 1 ; mode=block
Referrer-Policy: no-referrer
connection: close
 
{"status":401,"type":"UNAUTHORIZED","detail":"Invalid Bearer JWT Token"}

**Comment by franthemanIT** [comment]
Io userei l'URL INAD di collaudo:

https://domiciliodigitaleapi.oscl.infocamere.it/rest/inad/v1/domiciliodigitale

**Comment by Lovecraft81** [comment]
Perfetto grazie, nella documentazione non avevo trovato questo link. Ora funziona.
