### ISSUE TITLE
Caso di test non funzionante

### ISSUE THREAD

**Issue by Signo23** [AgID/INAD_API_Extraction#32]
Testando il metodo `verificaDomicilioDigitale` delle API di estrazione puntuale con i seguenti dati
```
codice_fiscale: 'TRVVCN73H02L259I',
digital_address: 'test@pec.it',
since: '2024-06-17'
```
 il valore di `outcome` è `false` nonostante ci si aspetti sia `true`

**Comment by vintra73** [comment]
buongiorno, 
abbiamo riscontrato un disalineamento tra i dati in curret e hystory, conseguenza di alcune azioni fatte sul DB, possiamo chiedervi di riprovare la chiamata? 

grazie

**Comment by Signo23** [comment]
Adesso sembra funzionare, grazie mille!
