### ISSUE TITLE
Errore nell'interrogazione stato richiesta elenco domicilio digitale

### ISSUE THREAD

**Issue by dominickgl** [AgID/INAD_API_Extraction#33]
Salve,
da alcuni test effettuati, ci siamo accorti che riceviamo un errore 401 effettuando la  richiesta di verifica dello stato degli elenchi digitali.
La cosa strana è che riceviamo due risposte contemporaneamente, nel senso che la prima contiene la risposta corretta, la seconda da un errore 401.
Allego screen  fiddler delle chiamate:

![image](https://github.com/user-attachments/assets/3d9062b8-0cdf-4c8f-a4ce-59bfa32d55a5)

Qui il dump della chiamata:

GET https://domiciliodigitaleapi.oscl.infocamere.it/rest/inad/v1/domiciliodigitale/listDigitalAddress/state/fc341af5-79a8-4abb-8119-558784a913f2 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6ImNkYjUyNTMyLWRkOTQtNDBlZi04MjRkLTljNTViMTBlNmJjOSJ9.eyJhdWQiOiJkb21pY2lsaW9kaWdpdGFsZWFwaS5vc2NsLmluZm9jYW1lcmUuaXQiLCJzdWIiOiJhNmFlNmE3OC1hYzdkLTRlOTItYWEyNS01YjA0M2JmOTAzYmEiLCJuYmYiOjE3MzA4ODI4OTQsInB1cnBvc2VJZCI6ImNhODgxMWIyLWMzYjktNGU3NS05Zjc1LTQ2ZWI3ODU4OGY1MSIsImlzcyI6InVhdC5pbnRlcm9wLnBhZ29wYS5pdCIsImV4cCI6MTczMDk2OTI5NCwiaWF0IjoxNzMwODgyODk0LCJjbGllbnRfaWQiOiJhNmFlNmE3OC1hYzdkLTRlOTItYWEyNS01YjA0M2JmOTAzYmEiLCJqdGkiOiJhNTc1ZDk0Ni0wM2Q2LTQyNjktODYzMy0yMGI5ODcwOGI1OTAifQ.bhFSB9RZ86nvh4N-tA5loXgZy33TImv2qGd9lXcvNE63F2Nutu1EYqpEcGGMHiaXY5TdqNIM1FIzNXj_e1Vp1WrHvCd66a-di8UuRvK9qs3Ok8nxbFjP-0MljhQGuPy2ge032A53fMGh6RV7tH2HrvatW0R1ixckt_SQc-96Drb8OrQp0mJ_yQalxpFNRK0vwQgMX50OFMOS-wNQXW5HPhAMbfkT9f4UTz_J3qHC4LzDBrJul0-dBvPz8A-JZ6QYg4Fk9U9RmU60hRWt4fcIER4Q7v3uVGgqOnbKQCNsqGxIU2yP4VLnknvpEJk4t5XC9PHsrANpE4RgbPLRfvGneQ
Content-Type: application/x-www-form-urlencoded
Host: domiciliodigitaleapi.oscl.infocamere.it

HTTP/1.1 303 See Other
vary: Origin
vary: Access-Control-Request-Method
vary: Access-Control-Request-Headers
date: Wed, 06 Nov 2024 08:48:16 GMT
location: https://domiciliodigitaleapi.oscl.infocamere.it/rest/inad/v1/domiciliodigitale/listDigitalAddress/response/fc341af5-79a8-4abb-8119-558784a913f2
server: Apache
x-powered-by: Undertow/1
content-type: application/json;charset=UTF-8
content-length: 63
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
x-content-type-options: nosniff
strict-transport-security: max-age=31536000 ; includeSubDomains
x-frame-options: DENY
x-xss-protection: 1 ; mode=block
referrer-policy: no-referrer
set-cookie: 17a9180d23d574732d9a874d9078cc9f=7cdc8e094da884ebd64e400a4024fa7b; path=/; HttpOnly; Secure; SameSite=None

{"state":"DISPONIBILE","message":"Richiesta elenco completata"}

GET https://domiciliodigitaleapi.oscl.infocamere.it/rest/inad/v1/domiciliodigitale/listDigitalAddress/response/fc341af5-79a8-4abb-8119-558784a913f2 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Host: domiciliodigitaleapi.oscl.infocamere.it

HTTP/1.1 401 Unauthorized
content-type: application/json
content-length: 74
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
x-content-type-options: nosniff
strict-transport-security: max-age=31536000 ; includeSubDomains
x-frame-options: DENY
x-xss-protection: 1 ; mode=block
referrer-policy: no-referrer
set-cookie: 17a9180d23d574732d9a874d9078cc9f=7cdc8e094da884ebd64e400a4024fa7b; path=/; HttpOnly; Secure; SameSite=None

{"status":401,"type":"UNAUTHORIZED","detail":"Bearer JWT Token not Found"}

Grazie in anticipo.

**Comment by dominickgl** [comment]
Ci siamo accorti che questo comportamento avviene appena lo stato diventa "disponibile".

Eseguendo un test con postman riceviamo una risposta che non è quella che dovremmo aspettarci, cioè quella dello stato della richiesta, ma quella della response con la lista dei codici fiscali, allego screen :

![image](https://github.com/user-attachments/assets/f0afea4e-bbee-463f-bdda-9ef0d559b798)


Grazie in anticipo.

**Comment by franthemanIT** [comment]
Penso che il problema sia che la risposta 303 è un reindirizzamento al link per prelevare la lista dei domicili digitali elaborati.

Nel primo scenario il reindirizzamento viene eseguito senza ripetere il token nell'header.
Postman, evidentemente lo ripete.

Probabilmente conviene disabilitare il reindirizzamento "automatico" per avere più controllo sulla situazione (o mantenere il token nell'header).

**Comment by dominickgl** [comment]
Ma noi facciamo una chiamata singola per prelevare solo lo stato. perchè dovrei reindirizzare la chiamata?

**Comment by franthemanIT** [comment]
Non so cosa usi per fare le chiamate, ma, per esempio, requests di Python segue il redirect di default a meno che non gli dai parametro allow_redirects = False.

L'header della response con status 303 ha un location: https://domiciliodigitaleapi.oscl.infocamere.it/rest/inad/v1/domiciliodigitale/listDigitalAddress/response/fc341af5-79a8-4abb-8119-558784a913f2 che è l'url chiamato quando ottieni risposta 401. La differenza è un "response" al posto di uno "state".

**Comment by dominickgl** [comment]
Infatti, impostando l'allow a false ricevo solo la risposta dello stato.
La chiamata è fatta in  c# tramite  HttpWebRequest ed il parametro da impostare è AllowAutoRedirect = false, qualora fosse utile a qualcuno.
Grazie e buona serata.
