### ISSUE TITLE
RISOLTO - Trust fra fruitore ed erogatore

### ISSUE THREAD

**Issue by franthemanIT** [AgID/INAD_API_Extraction#5]
Il README qui su GitHub menziona la PDND come intermediario per stabilire il trust fra erogatore e fruitore.

La PDND non è mai menzionata nelle specifiche tecniche delle API: https://domiciliodigitale.gov.it/dgit/home/public/docs/inad-specifiche_tecniche_api_estrazione.pdf

Le specifiche pero' ai paragrafi 4.2 e 4.3 descrivono un processo che è del tutto simile a quello che si fa su PDND per ottenere il token JWT da spendere nell'header delle chiamate all'e-service.

Si deve intendere che quanto descritto ai paragrafi 4.2. e 4.3 si fa con la PDND?

**Comment by franthemanIT** [comment]
Segnalo inoltre che ci sono altri disallineamenti fra specifiche tecniche testuail e file YAML, per esempio gli URL dei servizi.

**Comment by vintra73** [comment]
buongiorno,
le confermo che va applicato quanto indicato nel presente repo, stiamo correggendo i refusi nel documento  https://domiciliodigitale.gov.it/dgit/home/public/docs/inad-specifiche_tecniche_api_estrazione.pdf
