### ISSUE TITLE
Verifica del domicilio digitale senza codice fiscale: richiesta di evoluzione

### ISSUE THREAD

**Issue by franthemanIT** [AgID/INAD_API_Extraction#7]
Proposta: consentire di reperire informazioni su registrazione e titolare di un domicilio digitale senza fornire il codice fiscale.

Caso d'uso:
- l'art 65 c. 1 lett. c-bis del CAD prevede che l'istanza e la comunicazione inviate dal domicilio digitale registrato nei 3 registri (INAD, INIPEC, IPA) è valida (anche se non provvista di firma digitale, cioè);
- questo rende necessario verificare che la casella certificata da cui si riceve il messaggio sia domicilio digitale registrato dell'autore di istanza o comunicazione;
- siamo fuori da una procedura di presentazione di istanze guidata, quindi il sistema (protocollo informatico, direi) che riceve il messaggio non ha il codice fiscale del mittente come dato strutturato, non è quindi possibile invocare un automatismo per verificare se la casella mittente e' un domicilio digitale registrato dal mittente;
- un controllo semimanuale risulterebbe oneroso e disfunzionale (per via dei volumi) e talvolta impossibile (esistono casi in cui il mittente è chiaramente identificabile ma non se ne conosce il codice fiscale - ripeto, siamo in un contesto di trasmissione di documenti non guidata);
- invece, un controllo (anche da fare solo ed esclusivamente via API) che dall'indirizzo della casella fornisce riposta con codice fiscale (e magari nome e cognome) del titolare, potrebbe consentire di automatizzare la verifica se la casella mittente è un codice fiscale;
- la corrispondenza fra titolare del domicilio digitale e intestatario/autore dell'istanza/comunicazione può poi essere demandato a chi cura l'istruttoria del procedimento o le attività conseguenti.

**Comment by vintra73** [comment]
Buongiorno, 
le segnalo che i modelli di consultazione dell'INAD sono stati definiti nelle LG INAD emanate ai sensi dell'articolo 71 del CAD, che il sentito dekle amministrazioni competenti e del Garante per la protezione dei dati personali nelle materie di competenza, nonche' acquisito il parere della Conferenza unificata.

**Comment by franthemanIT** [comment]
Grazie anche per questo. Confermo che le API ricalcano in modo impeccabile il dettato delle linee guida.

L'art. 65 però, pur nella sua continua mutevolezza, sembrerebbe richiedere anche forme di verifica della registrazione di un indirizzo di posta certificata (PEC, REM o SERCQ che dir si voglia) come DD e conoscerne il titolare. 
Infatti, con stupore, sembra di capire che la nuova REM non veicolerà alcun dato identificativo del mittente (cosa che pare impedire controlli automatici alla ricezione del messaggio).

Io ente pubblico che processo metto in piedi per capire se accettare o meno una comunicazione da una PEC/REM e come posso automatizzarlo?
Trattandosi di questione legislativa, a chi ci si può rivolgere per un confronto?
Non è poi escluso che il risultato sia raggiungibile, con un workflow che a me personalmente non viene in mente.

**Comment by vintra73** [comment]
Buongiorno,
in merito alla sua esigenza di approfondire il tema le riporto il riferimento della collega AgID Alessandra Antolini (antolini@agid.gov.it) che segue il tema PEC/REM.
