### ISSUE TITLE
Servizio recupero stato di una lista - URL errata nel redirect

### ISSUE THREAD

**Issue by franthemanIT** [AgID/INAD_API_Extraction#9]
Salve, 
ho fatto una prova con un'estrazione massiva : /listDigitalAddress e collegati.
Tutto bene, però rispetto alle specifiche:
- Con lista in stato "in elaborazione" ricevo lo status code atteso.
- quando la lista è pronta non ricevo una response con status code 303 ma con status code 404 (not found).

Poi il recupero della lista di domicili funziona.

Vi copio qualcosa che può essere utile:

Risposta a lista pronta:

`"timestamp": "2023-06-15T17:40:14.600+00:00",
	"status": 404,
	"error": "Not Found",
	"path": "/v1/domiciliodigitale/elenco/3d271191-0d20-4693-8f5f-48ad49fcec9f/risultato"`

Recupero della lista:

`{
	"list": [
		{
			"codiceFiscale": "**************",
			"since": "2023-06-15T19:40:00Z",
			"digitalAddress": [
				{
					"digitalAddress": "***@****.it"
				}
			]
		},
		{
			"codiceFiscale": "*********",
			"since": "2023-06-15T19:40:00Z",
			"digitalAddress": [
				{
					"digitalAddress": "*****@***.it"
				}
			]
		},
		{`

PS: ho ricevuto un elenco di codici fiscali censiti in ambiente di test dal supporto Infocamere, li ho oscurati.

**Comment by franthemanIT** [comment]
Fatte ulteriori verifiche.
In effetti lo status 303 è un redirect.
Dai miei log ottengo questo:
`https://domiciliodigitaleapi.oscl.infocamere.it:443 "GET /rest/inad/v1/domiciliodigitale/listDigitalAddress/state/849cbb54-a4fa-4b73-bcd3-70b1a2862f9f HTTP/1.1" 303 63
https://domiciliodigitaleapi.oscl.infocamere.it:443 "GET /rest/inad/v1/domiciliodigitale/elenco/849cbb54-a4fa-4b73-bcd3-70b1a2862f9f/risultato HTTP/1.1" 404 163`

Probabilmente il redirect reindirizza a un URL non valido, infatti la lista la recupero dalll'URL:
`https://domiciliodigitaleapi.oscl.infocamere.it:443 "GET /rest/inad/v1/domiciliodigitale/listDigitalAddress/response/849cbb54-a4fa-4b73-bcd3-70b1a2862f9f HTTP/1.1" 200 870`

**Comment by vintra73** [comment]
Abbiamo fizzato l'UTL dell'header location riportando https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/listDigitalAddress/response
